# Generated by Django 4.2.5 on 2023-12-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todolist", "0002_task_create_at_task_description_task_last_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("L", "Low"), ("M", "Medium"), ("T", "Top")],
                max_length=1,
                null=True,
            ),
        ),
    ]
